[pyprland]
plugins = [
 "scratchpads",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.term]
animation = "fromTop"
# command = "[term_classed] main-dropterm"
command = "kitty"
# class = "main-dropterm"
class = "kitty"
size = "75% 60%"
max_size = "1920px 100%"
